language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.6.x.zip
  - DJANGO_PACKAGE=Django==1.5.1
  - DJANGO_PACKAGE=Django==1.4.5
install:
  - pip install -q $DJANGO_PACKAGE --use-mirrors
  - pip install --use-mirrors .
script:
  - python setup.py test
